### PR TITLE
Version 5.0

### PR DESCRIPTION
**Pull request by marcingminski**

### CODE REVIEW

**Comment by sozezzo** [comment]
The select environment is hardcoded to use the database [SQLWATCH]

image

**Comment by jjjan** [comment]
add support linux sql server on version 5

**Comment by marcingminski** [comment]
> add support linux sql server on version 5

Hi, have you tried it on Linux at all? Apart from WMI, which is Windows-specific, everything should work.

**Comment by jjjan** [comment]
> > add support linux sql server on version 5
> 
> Hi, have you tried it on Linux at all? Apart from WMI, which is Windows-specific, everything should work.

Thanks to replay me. when i deploy dacpac i face issue on sqlserver 2019 based linux docker.
ok i am ready if you have any solution for that beside dacpac file. i also test version 3 and i also facing issue again. so what's your idea about sqlserver 2018 based on linux docker

**Comment by jjjan** [comment]
> > add support linux sql server on version 5
> 
> Hi, have you tried it on Linux at all? Apart from WMI, which is Windows-specific, everything should work.

you right can i have index fragmentation monitor for all index?

**Pull request closed without merging**
