### PR TITLE
Fixing the problem if you have indexes with the same name

### PR DESCRIPTION
**Pull request by PlayMan86**

### CODE REVIEW

**Review by marcingminski — COMMENTED** [review]
Hi, Thanks. Can you confirm what the actual change is? Is it just the order of INNER JOINs? When it comes to INNER JOINs, the order does not matter. Just to be on the safe side, can you tell me what the issue is? Indexes with the same name as long as they belong to different tables should be ok. I do not think it is possible to have an index with the same name on the same table.

If you could provide an example of the duplication so I can see it or even replicate on my side that would be great.

 Thank you for your help.

**Comment by PlayMan86** [comment]
The problem is with indexes on different tables but with the same name. 
There is not only the order of inner joins.
image
On the inner join inner join on mdb table it should be enough to check database name and create_date, this should be like unique.

**Comment by marcingminski** [comment]
Ok, thank you. Let me try to replicate this on my side.

**Comment by PlayMan86** [comment]
I have tested it, with removing/creating/renaming databases. I couldn't find any issue. But of course, is better when some test it too.

**Comment by PlayMan86** [comment]
On originally Stored Procedure if I have more than one index with the same name, I am getting that error:

` Violation of PRIMARY KEY constraint 'pk_index_usage_stats'. Cannot insert duplicate key in object 'dbo.sqlwatch_logger_index_usage_stats'. The duplicate key value is (2020-04-23 17:31:44, 3a43f53f5033, 6, 335, 90, -1, 14).`
I took the process_message from sqlwatch_app_log and executed it without insert, to see the rows and added some columns (database name, table name, index name) at the start, so you can see what I mean.
image
As you can see, there are duplicated sqlwatch_index_id, that's why it can not be imported in the table.

**Pull request merged**
