### PR TITLE
Fixed missing query details in report views and Grafana dashboard.

### LINKED ISSUE #344: Grafana Dashboard - "SQL Instance Overview>Long Queries/Wait Events" panels missing details, displays missing field(s) error
**Did you check DOCS to make sure there is no workaround?**
Yes

**Describe the bug**
When viewing the 'SQL Instance Overview' in the Grafana dashboard, missing fields prevent the Long Queries/Wait details to display

**To Reproduce**
1. Install SQL Instance Overview > Grafana dashboard via the SQL Instance Overview.json 
2. Force long running query or wait

**Expected behavior**
Expect to see the details of any long running queries display in the panel
 
**Additional context**
There were 3 fields (sql_text, database_name and object_name) removed from vw_sqlwatch_report_fact_xes_long_queries in the 4.0 release that were utilized by these dashboards. This could be fixed in a couple different ways, either we add the query plan hash statement from sqlwatch_meta_query_plan_hash to the view (this will get us the sql text but not database name or object name) or we modify the dashboard query to join sqlwatch_logger_xes_long_queries/sqlwatch_logger_xes_wait_event and parse out the event_data (this will get us the sql text and database name). The latter also gives us the 'real' sql that caused the long query which may be crucial. I like the second method as the actual SQL text may not be needed when executing the view(s). I have made a changes using the second method and will be sending a PR. Let me know if there is another preference.

### PR DESCRIPTION
**Pull request by TArmstrong24**
Added Database name, procedure name and sql_text to views utilized by reports. Also update the Grafana dashboard to remove field that is no longer needed.

### CODE REVIEW

**Comment by marcingminski** [comment]
Fix #344

**Review by marcingminski — COMMENTED** [review]
Just thinking that since the `replace(replace(replace(replace(replace(coalesce(qph.statement_for_query_plan_hash,[event_data].value('(event/action[@name="sql_text"]/value)[1]', 'varchar(max)')),char(9), ''),char(10),'') ,' ',char(9)+char(10)),char(10)+char(9),''),char(9)+char(10),' ')` is used twice in two views, we could have that piece of code in a scalar function? 
Or, depending on the performance, a table valued function where we would pass the xml?

**Comment by TArmstrong24** [comment]
I was actually thinking along the same lines but I didn't know if it would have enough value outside of this instance.  A scalar function focused just on the cleanup of the SQL text, not including the XML parsing, sounds clean and reusable. ufn_sqlwatch_clean_sql_text?

**Comment by marcingminski** [comment]
I often catch myself making changes to the code just to then find a copy of the same piece elsewhere so decided to either create a function or procedure for any code used more than once. This is for maintainability rather than end-user experience.
Looking at the existing functions, there are a few that parse stuff already: `ufn_sqlwatch_parse_sql_text`?

**Comment by TArmstrong24** [comment]
Trying not to overthink it :).. but maybe a table-valued function would be better for the sake of reusability. Then it could be used if other fields from the event_data XML are needed. So `ufn_sqlwatch_parse_xes_event_data` ? Which is probably more likely than just needing to 'clean' up some sql text...

**Comment by marcingminski** [comment]
I was recently thinking about a generic function or procedure to parse all the xml data. That may be a good approach but not sure how complex it would have to be to be completely generic. I suppose it will be case of it being generic or fast.

Have a go if you fancy it

**Comment by TArmstrong24** [comment]
I actually ended up creating two functions, one to cleanup the SQL text since we need it for SQL text that is already saved outside the event data, and one to parse and format the event data which reuses the cleanup function.

**Comment by marcingminski** [comment]
Thats great. Thank you. Could I ask you to follow Codacy suggestions and add terminators to your statements please? I was going to remove this particular check but then MS recommends semicolon terminators so may as well stick to it. Thanks
https://github.com/marcingminski/sqlwatch/pull/347/checks?check_run_id=2560066503

**Comment by marcingminski** [comment]
What is your opinion on the semicolon check? I am torn, the amount of semicolons I have to add to make the Codacy happy is crazy but then again MS recommends semicolons...

**Comment by marcingminski** [comment]
Looks like there is a number of build errors, start at Line 136:
https://ci.appveyor.com/project/marcingminski/sqlwatch/builds/39120830

By looking at it, what seems to have happened is that the new objects are not in the VS Project. And it seems right because I do not see the project files as part of the commit. I may be able to fix this by adding these objects and pushing updated projects files unless you have done those changes via Visual Studio? Don't worry if not, I will try sort this out.
```
Build error SQL71501: View: [dbo].[vw_sqlwatch_report_fact_xes_wait_events] has an unresolved reference to object [dbo].[ufn_sqlwatch_parse_xes_event_data]. [C:\projects\sqlwatch\SqlWatch.Monitor\Project.SqlWatch.Database\SQLWATCH.sqlproj]
C:\projects\sqlwatch\SqlWatch.Monitor\Project.SqlWatch.Database\dbo\Views\vw_sqlwatch_report_fact_xes_wait_events.sql(23,15,23,15): Build error SQL71501: View: [dbo].[vw_sqlwatch_report_fact_xes_wait_events] contains an unresolved reference to an object. Either the object does not exist or the reference is ambiguous because it could refer to any of the following objects: [dbo].[sqlwatch_logger_xes_wait_event].[dbo]::[ufn_sqlwatch_clean_sql_text], [dbo].[sqlwatch_meta_database].[dbo]::[ufn_sqlwatch_clean_sql_text], [dbo].[sqlwatch_meta_procedure].[dbo]::[ufn_sqlwatch_clean_sql_text], [dbo].[sqlwatch_meta_query_plan].[dbo]::[ufn_sqlwatch_clean_sql_text], [dbo].[sqlwatch_meta_query_plan_hash].[dbo]::[ufn_sqlwatch_clean_sql_text], [dbo].[ufn_sqlwatch_clean_sql_text], [dbo].[ufn_sqlwatch_parse_xes_event_data].[dbo]::[ufn_sqlwatch_clean_sql_text] or [dbo].[vw_sqlwatch_meta_wait_stats_category].[dbo]::[ufn_sqlwatch_clean_sql_text]. [C:\projects\sqlwatch\SqlWatch.Monitor\Project.SqlWatch.Database\SQLWATCH.sqlproj]
C:\projects\sqlwatch\SqlWatch.Monitor\Project.SqlWatch.Database\dbo\Views\vw_sqlwatch_report_fact_xes_wait_events.sql(23,82,23,82): Build error SQL71501: View: [dbo].[vw_sqlwatch_report_fact_xes_wait_events] contains an unresolved reference to an object. Either the object does not exist or the reference is ambiguous because it could refer to any of the following objects: [dbo].[sqlwatch_logger_xes_wait_event].[ed]::[sql_text], [dbo].[sqlwatch_meta_database].[ed]::[sql_text], [dbo].[sqlwatch_meta_procedure].[ed]::[sql_text], [dbo].[sqlwatch_meta_query_plan].[ed]::[sql_text], [dbo].[sqlwatch_meta_query_plan_hash].[ed]::[sql_text], [dbo].[ufn_sqlwatch_parse_xes_event_data].[ed]::[sql_text], [dbo].[ufn_sqlwatch_parse_xes_event_data].[sql_text] or [dbo].[vw_sqlwatch_meta_wait_stats_category].[ed]::[sql_text]. [C:\projects\sqlwatch\SqlWatch.Monitor\Project.SqlWatch.Database\SQLWATCH.sqlproj]
C:\projects\sqlwatch\SqlWatch.Monitor\Project.SqlWatch.Database\dbo\Views\vw_sqlwatch_report_fact_xes_long_queries.sql(52,14,52,14): Build error SQL71501: View: [dbo].[vw_sqlwatch_report_fact_xes_long_queries] has an unresolved reference to object [dbo].[ufn_sqlwatch_parse_xes_event_data]. [C:\projects\sqlwatch\SqlWatch.Monitor\Project.SqlWatch.Database\SQLWATCH.sqlproj]
C:\projects\sqlwatch\SqlWatch.Monitor\Project.SqlWatch.Database\dbo\Views\vw_sqlwatch_report_fact_xes_long_queries.sql(26,15,26,15): Build error SQL71501: View: [dbo].[vw_sqlwatch_report_fact_xes_long_queries] contains an unresolved reference to an object. Either the object does not exist or the reference is ambiguous because it could refer to any of the following objects: [dbo].[sqlwatch_logger_snapshot_header].[dbo]::[ufn_sqlwatch_clean_sql_text], [dbo].[sqlwatch_logger_xes_long_queries].[dbo]::[ufn_sqlwatch_clean_sql_text], [dbo].[sqlwatch_meta_database].[dbo]::[ufn_sqlwatch_clean_sql_text], [dbo].[sqlwatch_meta_procedure].[dbo]::[ufn_sqlwatch_clean_sql_text], [dbo].[sqlwatch_meta_query_plan].[dbo]::[ufn_sqlwatch_clean_sql_text], [dbo].[sqlwatch_meta_query_plan_hash].[dbo]::[ufn_sqlwatch_clean_sql_text], [dbo].[ufn_sqlwatch_clean_sql_text] or [dbo].[ufn_sqlwatch_parse_xes_event_data].[dbo]::[ufn_sqlwatch_clean_sql_text]. [C:\projects\sqlwatch\SqlWatch.Monitor\Project.SqlWatch.Database\SQLWATCH.sqlproj]
C:\projects\sqlwatch\SqlWatch.Monitor\Project.SqlWatch.Database\dbo\Views\vw_sqlwatch_report_fact_xes_long_queries.sql(26,82,26,82): Build error SQL71501: View: [dbo].[vw_sqlwatch_report_fact_xes_long_queries] contains an unresolved reference to an object. Either the object does not exist or the reference is ambiguous because it could refer to any of the following objects: [dbo].[sqlwatch_logger_snapshot_header].[ed]::[sql_text], [dbo].[sqlwatch_logger_xes_long_queries].[ed]::[sql_text], [dbo].[sqlwatch_meta_database].[ed]::[sql_text], [dbo].[sqlwatch_meta_procedure].[ed]::[sql_text], [dbo].[sqlwatch_meta_query_plan].[ed]::[sql_text], [dbo].[sqlwatch_meta_query_plan_hash].[ed]::[sql_text], [dbo].[ufn_sqlwatch_parse_xes_event_data].[ed]::[sql_text] or [dbo].[ufn_sqlwatch_parse_xes_event_data].[sql_text]. [C:\projects\sqlwatch\SqlWatch.Monitor\Project.SqlWatch.Database\SQLWATCH.sqlproj]
```

**Comment by TArmstrong24** [comment]
Didn't think about adding them to VS project. I can add them real quick so that everything is at least part of the same PR.

**Comment by marcingminski** [comment]
Magic, thank you!

**Comment by marcingminski** [comment]
That is building OK now. Thank you

**Comment by TArmstrong24** [comment]
> What is your opinion on the semicolon check? I am torn, the amount of semicolons I have to add to make the Codacy happy is crazy but then again MS recommends semicolons...

Seems like Codacy is a little fussy... but keeping structure/formatting consistent while following MS guidelines is good and adding the semicolons is painless so probably best to keep the check.

**Comment by marcingminski** [comment]
Yeah that was my thinking too, just do not want to put people off contributing :)
Thank you for your help with this. It's been a pleasure!

**Comment by marcingminski** [comment]
Just a quick question regarding this change. The SQL Cleanup function seems to be removing carriage return characters from SQL Text. When shown in Grafana, I think it looks worse than the original sql text. Was this the intention of this change?

Result when using `dbo.ufn_sqlwatch_clean_sql_text`:
image

and without:
image

**Comment by TArmstrong24** [comment]
Yes, that was the intention of the change. I don't have the exact statement I was using to run the test but the situation I encountered was working with short queries. Without the removal of formatting, the statement would force a new line when the display grid had plenty of vertical space. When I removed the carriage returns I then saw all the extra whitespace which looked worse. I would rather have the view control the formatting based on available space rather than have it hard coded in the text. Although I do see the benefit of having the carriage returns (if they exist) as that may better format the text if you want statement separation. Maybe the cleanup could just remove the whitespace (which I don't see any advantage of having) and then carriage returns could be removed on the front end if desired?

**Comment by marcingminski** [comment]
Do you mean white spaces like this:
image

Yeah, I would agree remove the wite spaces but leave carriage returns

**Comment by TArmstrong24** [comment]
Yes, exactly. That sounds good to me.

**Comment by marcingminski** [comment]
Great, I will get that sorted. Thanks

**Comment by marcingminski** [comment]
is that acceptable? same query as above
image

**Comment by TArmstrong24** [comment]
Look good!

**Comment by marcingminski** [comment]
Actually, what I may do, instead of using the "log" panel which requires a query, I may just use markdown text panel and populate SqlText from variable, which we already have in the "Queries" panel. The downside is that the Grafana variables do not seem to carry on the carriage return:
image
I may need a chat with Grafana devs to see if there is a workaround. 
The benefit is that we're querying the database once, instead of twice for the same data.

**Pull request merged**
