### PR TITLE
Minor style suggestions

### PR DESCRIPTION
**Pull request by DavidBetteridge**
These changes/comments are personal preference so feel free to ignore them!

The code in SqlWatchInstance could be broken down into more functions.  I've added the method SnapshotTimeForInstance as an example.   This makes the code easier to maintain and also reduces bugs by reducing the scope of variables.  For example in this case the variable sql in only valid within the method.

It's bad practice to build sql by joining strings.  I've amended the code to use a parameter @SqlInstance instead.

Use the correct types where possible.  In this case I'm returning a type of DateTime rather than string to hold the snapshot date.

Disclaimer.  The code compiles but I've no idea if it will run!

### CODE REVIEW

**Comment by marcingminski** [comment]
Thank you kindly! I will give this a go in my test setup.

**Comment by marcingminski** [comment]
Thank you for your input David. As someone who is learning C# your input is really appreciated and valued. 
As a database person, I usually tell developers off for not using the right data types :-) so I'm with you on that one! In the case of `SnapshotTimeForInstance`  (`snapshotTimes`) however, we are returning an actual string not a single date. Maybe the name `snapshotTimes` is a bit misleading but I kept it plural for that reason. The output is a `case when` with the latest date for each snapshot type, not a single date. 

image

The only exception will be on the first run when there are no snapshot times, then we are going to default to a single date of `1970-01-01`

Agree I should be using parameters instead of joining strings. No excuse there.

Having said all that, I take your point about breaking down the code into functions. That's something I will certainly try to improve in the future.

**Comment by marcingminski** [comment]
I am going to keep your proposed changes but will change the `SnapshotTimeForInstance` to return `string` instead of `date`. I may also change the name to `SnapshotTimesForInstance` (plular) . 

(I am not sure if there are any rules in C# but in the database world we like to keep things singular as it's an entity, not a collection of items) although I don't always stick to this rule. 

I will report back after more testing.

**Comment by DavidBetteridge** [comment]
Ah I see,  it's returning sql to be used in the where clause,  rather than just a single time.  I don't think it really matters in this case,  but I would  have gone for returning some form of list of snapshot_type_id+time from the function and then building up the sql in code.

In terms of naming,  the same sql rules don't really apply.  If a function returns a single time, then it has a singular name.  (In this case it would have a plural name)

**Comment by marcingminski** [comment]
A list sounds like a much better  approach. I’m not sure why I hadn’t thought of that.  I’ll add it to my to do. Thank you for the suggestion.

**Pull request merged**
