### PR TITLE
#378 Replace localhost with @@servername

### PR DESCRIPTION
**Pull request by steffenengelhamburg**
see #378

### CODE REVIEW

**Comment by marcingminski** [comment]
Can you please review Codacy suggestions please? It is currently failing on the missing batch terminators.

**Comment by steffenengelhamburg** [comment]
Hi Marcin,
added the Semicolon as suggested, but got a Sonarcloud Error? Don‘t know what this means.

I marked this PR now as Draft PR…

Viele Grüße

Steffen

**Comment by marcingminski** [comment]
Thank you. Don't worry about SonarCloud, its rubbish I am going to remove it. Looks good now.

**Comment by marcingminski** [comment]
I do not think I can merge now since you have changed it to draft.

**Review by steffenengelhamburg — COMMENTED** [review]
All suggested Fixes done

**Pull request merged**
